### ISSUE TITLE
Flush cache immediately after site is put into maintenance mode

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#106]
I would recommend moving the cache flush and varnish ban commands immediately after the `magento:maintenance:enable` command runs when doing a deployment:

![22-02-31 1 bash-fmjqj](https://user-images.githubusercontent.com/129031/38909681-452a8fd0-428b-11e8-96ff-43a6294fc55b.jpg)

The reason for this is that many pages will be cached in Varnish, and if a user tries to do anything with those pages that requires interaction from the server (e.g., add a product to the cart), they will get an error or a spinner that never goes away. And so rather than providing an inconsistent experience to users, it seems that putting all pages in maintenance mode will avoid confusion as you're upfront with the user about the site being offline.

I'm currently in the middle of deploying an update to a server, updating Magento 2.1.x to 2.2.x. The `magento:setup:db:data:upgrade` step is going to take about 30 minutes due to the size of the merchant's database. To avoid the inconsistent experience mentioned above, I flushed the cache on the server right after the `magento:maintenance:enable` step. It's far more common for the site to only be in maintenance mode for a couple of minutes, but my point stands that it provides the most consistent experience to flush the cache immediately after the site is put _into_ maintenance mode, not right after it's taken _out of_ maintenance mode.

**Comment by davidalger** [comment]
I think you have the wrong repository @erikhansen ;) Can you re-create this over on the [capistrano-magento2 issues tab](http://github.com/davidalger/capistrano-magento2/issues) for me?
