### ISSUE TITLE
Map certain host commands to wrapper script which runs command in VM

### ISSUE THREAD

**Issue by ericthehacker** [davidalger/devenv#24]
In order to ensure 100% consistent behavior, it could possibly be helpful to have certain commands configured on the host to be a shell script which hops inside the VM and runs the original command there.

These are some example such commands:
- php (possibly restricted to only run in VM if under /sites, run on host overwise)
- mr
- composer

**Comment by ericthehacker** [comment]
`bin/magento` would be another good candidate.

**Comment by davidalger** [comment]
Closing as resolve in develop. The new version of `vcd` there supports running commands either on the default vm or the specified vm:

* vcd php -v — runs on default vm
* vcd web56 php -v

There is currently one wrapper:

* `magento` — this will execute the `magento` command inside a vm, ultimately calling through to the `bin/magento` CLI tool found in the project of the CWD.

It would be trivial to add more and PRs with the addition of new ones would be considered (on an individual basis). Wrapping generic commands such as php and composer would likely not be considered, however, as they would inevitably result in a users inability to easily run those commands directly on the host machine for projects which are not resident to this dev env.
