### ISSUE TITLE
Host php differs from vm client php

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/devenv#25]
The default installed OS X version of PHP installed has some missing php extensions that are necessary for Magento 2.

I installed PHP 5.6 using brew and the associated php extensions as a workaround:

```
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php56
brew install homebrew/php/php56-mcrypt
brew install homebrew/php/php56-redis
brew install homebrew/php/php56-intl
```

This lets me run `bin/magento cache:flush`, `indexer:reindex`, and `setup:upgrade` from the host, which is convenient.

**Comment by davidalger** [comment]
Related: #24

**Comment by davidalger** [comment]
Closing. The install script now installs PHP 7.0 via brew on the host machine. There is no way to avoid having discrepancies and being cautious about which one you're using, however, as (for example) there is still a web56 and a web71 vm (on develop) which will naturally have disparate versions of PHP.

Additionally the `magento` wrapper for `bin/magento` will execute via `vcd` from directly inside the default and/or specified vm now.
