### ISSUE TITLE
Grunt support from within the VM

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/devenv#33]
I wanted to use grunt from within the VM, but ran into a few issues when trying to install it. I got it working, but had to update the kernel-headers to support getting npm installed. That updated the kernel-headers from v2.2 to v2.6.

```
sudo yum install kernel-headers --disableexcludes=all
sudo yum install npm
sudo npm install -g grunt-cli
```

**Comment by davidalger** [comment]
This should be supported in 1.0.0-beta10 once released.
