### ISSUE TITLE
Add https support in web machines

### ISSUE THREAD

**Issue by davidalger** [davidalger/devenv#34]
* should create a CA root on host machine (in .shared) which user may then add to the system key trust store
* virtual host template needs section added for secure requests
* nginx will need to be configured to listen on 443 for secure requests, proxying all secure requests to apache (or support ssl termination in nginx layer as well for static assets)
* vhosts.sh script should automatically sign a certificate (using shared CA root) for the virtual host when initially created

**Comment by ericthehacker** [comment]
@davidalger 
Just so you know, I'm actively working on implementing this and should have a PR within a few days.
