### ISSUE TITLE
possible WSDL issue

### ISSUE THREAD

**Issue by ericthehacker** [davidalger/devenv#36]
Based on our conversation, due to the fact that the VM does not have custom host entries, it probably can't reach out to itself over HTTP.

Because of this, it's possible that this will break the Magento API, since Magento reaches out to itself over the network to get its WSDL file.

**Comment by davidalger** [comment]
This will be fixed in the next tagged release. The vhosts.sh script now adds an entry to /etc/hosts for every domain it runs through to ensure valid local DNS is available for each site.
