### ISSUE TITLE
m2.dev Script using symbolic links for var dir not working

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/devenv#39]
I ran into an issue when setting up the m2.dev site in how it uses the symbolic linking for the var directories. 

It worked fine from the browser, but if I tried to shell into the server and run bin/magento command from the console I had permission issues due to the fact that Apache was running as a different user than the vagrant user I logged into the shell with.

To resolve the issue I deleted the symbolic links and had Magento rebuild the var directories files under the /sites dir. I believe that because this is mounted through NFS, it forces permissions so they work for either Apache or the vagrant user.

**Comment by davidalger** [comment]
Will be resolved in 1.0.0-beta10 once released.

**Comment by davidalger** [comment]
Note: To resolve this on current installations, simply run the following one-liner (from the host machine):

rm -rf /server/var/ /server/sites/m2.dev/var/*
