### ISSUE TITLE
mysql db import slowness

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/devenv#44]
I've noticed that mysql imports tend to take a really long time so I started investigating a few different ways to import the database to the virtual machine.

This took 27 minutes to import a 180MB database.

```
pv /sites/m2esedev.dev/magento-database.sql | mysql -D test_import --default-character-set=utf8
```

This took 2 minutes to import the same file

```
vagrant ssh db -- 'mysql -uroot --password="" -D test_import --default-character-set=utf8 < /server/.shared/magento-database.sql'
```

I wanted to use pv to monitor large db import progress, and vagrant ssh appears to not work with pv. From what I was reading I think it's because the pv progress is reported to standard out and vagrant ssh is not reporting that back to the host. I decided to try it with the standard ssh client and pv works with that so I came up with this alternative.

This completed in 2 minutes and I got the progress from pipe viewer during import

```
pv /sites/m2esedev.dev/magento-database.sql | ssh dev-db 'mysql -uroot --password="" -D test_import --default-character-set=utf8'
```

In order to use the ssh command without specifying credentials on the command line like the `vagrant ssh` command I had to add ssh configuration options to my user account.

```
Host dev-db
  User vagrant
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /server/vagrant/.vagrant/machines/db/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

I don't understand why there is such a huge difference between executing the mysql import from the host machine, vs piping the file to the vm and executing it from within the virtual machine. It doesn't seem like it should be that slow when executed from the host.

**Comment by davidalger** [comment]
This should be resolved with the architectural changes on develop as the mysql database now resides within the same VM as the web server.
