### ISSUE TITLE
Nginx/MySQL timeout during long debugging sessions

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#45]
I frequently use PhpStorm to debug an application and leave my debugging session open for 1hr+. The problem with this is that both MySQL and Nginx have such short timeouts that by the time I resume my debugging session, one or both of them have timed out.

I've temporarily resolved the MySQL timeout by adding this to my index.php file:
```
$timeout = 7200; // 2 hours
ini_set('mysql.connect_timeout', $timeout);
ini_set('default_socket_timeout', $timeout);
```
This solves the problem with MySQL terminating my debugging session, but since Nginx times out, I'm unable to see the results of the page load and instead see this:

![screen shot 2015-11-06 at 4 22 04 pm](https://cloud.githubusercontent.com/assets/129031/11010178/89dba4e2-84a2-11e5-873b-954fef07cec1.png)

Since I can still complete my debugging process, I have not yet edited the Nginx file to increase the timeout, however I'm planning on doing that.

I'd like to implement a more permanent solution to this problem, as I expect I'm not the only one who runs into this issue. Would you accept a pull request that increases the MySQL and Nginx timeouts to 2 hours (or some other large value)? 

I realize this could have negative implications for non-debugging situations, so maybe it would be better to have a standard way to temporarily increase the timeout and restart Nginx for the change to take effect. 

~~Alternatively, maybe these settings could be triggered when a debug session is kicked off or at least when debugging is enabled (via the cookie or the `xdebug.remote_autostart=on` setting that the `php-debug` command sets).~~ UPDATE: I don't like this approach. I think a specific script that temporarily changes these settings would be ideal.

**Comment by mttjohnson** [comment]
The topic addressing nginx was previously discussed in #26

**Comment by erikhansen** [comment]
@mttjohnson Thanks. 10 minutes is definitely still too short for my purposes, so I would like to hear David's thoughts on a mechanism to temporarily increase the timeouts, either via a specific script or keyed off a cookie/xdebug setting.

**Comment by davidalger** [comment]
> I frequently use PhpStorm to debug an application and leave my debugging session open for 1hr+

My suggestion? Stop taking long snack breaks! ;)

More seriously though… this is an incredibly long time to expect a system (yes, even on development) to simply wait for you to pickup where you left off. You simply don't have requests which should take nearly this long to run (even in a debugger). Things that do take this long could/should be run from the CLI where an nginx proxy timeout wouldn't come into play.

>  I think a specific script that temporarily changes these settings would be ideal.

If you would like to create such a script and PR it to the `/server/vagrant/bin/` directory, I will consider accepting it, otherwise this is a no go :)

**Comment by erikhansen** [comment]
The snacks are just too irresistible. :candy:

PR submitted: #46
