### ISSUE TITLE
Install on new machine results in error when installing php56-redis

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#53]
I just tried installing devenv on a new machine that did not previously have brew, php, or other primary dependencies installed and ran into an error that prevented me from continuing. I got this error when brew tried to install php56-redis:

```
==> Checking pack homebrew/php/php56-redis
==> Installing brew homebrew/php/php56-redis
Error: No such file or directory - /usr/local/opt/igbinary/include/igbinary.h
```

I ran the following commands (from [this comment](https://github.com/Homebrew/homebrew-php/issues/1910#issuecomment-127398300)) and after doing so I was able to complete the devenv process.

```
brew remove php56-igbinary php56-redis 
brew reinstall php56 --enable-maintainer-zts --build-from-source php56-igbinary --build-from-source php56-redis --build-from-source
```

**Comment by erikhansen** [comment]
FYI - I just ran into this issue again installing devenv on a new MacBook that didn't have a previous development environment installed.

**Comment by davidalger** [comment]
The issue here is / was in the homebrew packages not this repository. Closing.
