### ISSUE TITLE
"Too many files open" error occurring frequently when running Magento 2

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#55]
Every few days, I run into an issue where the `/var/log/httpd/error_log` file on my web node is filled with error messages like this:

```
[Thu Jan 14 21:07:45 2016] [crit] [client 127.0.0.1] (24)Too many open files: /server/sites/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable
```

This is commonly caused when I delete the `var/view_preprocessed` and `pub/static/frontend` directories in my Magento 2 install and refresh.

The ulimit is currently set to 1024.It seems like the simple approach would be to raise the ulimit, however that may be treating the symptom, not the cause.

**Comment by erikhansen** [comment]
@mttjohnson has also reported experiencing this issue: _"Yes I have run into that issue... while running grunt and live reload on an M2 site... I rebooted the VM to make sure it cleared any open files."_  

While rebooting works, it's not a good long-term solution, especially considering that our developers are going to be doing M2 frontend development and will run into this issue more frequently.

**Comment by mttjohnson** [comment]
It would be nice if there was a consistent, or frequent way to reproduce this issue, otherwise it's not likely going to be addressed.

**Comment by erikhansen** [comment]
Over the weekend I tried to reproduce this using a couple different routes, but was not able to.

I tried deleting the `var/generation`, `var/view_preprocessed`, and `pub/static/frontend` directories and then refreshing the frontend and repeated that processes ~10 times but was not able to reproduce the issue. I'm closing this task and will only re-open if this becomes a problem.
