### ISSUE TITLE
Change m2setup.sh to be verbose by default

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#62]
There have been several times now where I've used the `m2setup.sh` script to install Magento where the script has silently failed for various reasons, but it's not apparent that the script has failed:

![m2setup](https://cloud.githubusercontent.com/assets/129031/14321650/bca1a14c-fbdf-11e5-9957-5d7f6e6fcc21.png)

<img width="826" alt="sites_ _vagrant_dev-web__server_sites_ _ssh_ _vcd_ _105x49" src="https://cloud.githubusercontent.com/assets/129031/14322206/9535b1d2-fbe1-11e5-963d-8d228c15df34.png">

I'd recommend changing the default behavior to verbose and then add a `-q` flag that can be used to suppress output.

**Comment by davidalger** [comment]
The solution I'm implementing here is to force composer into non-interactive mode when the sampledata:deploy is run to prevent the hangs. I've also added a trap to spit an error message out when a sub-command fails.
