### ISSUE TITLE
web55 and web54 php.ini xdebug settings differ from web node php.ini

### ISSUE THREAD

**Issue by adammprost** [davidalger/devenv#71]
The following variables differ between web55/web54 and web:
```
xdebug.file_link_format => no value => no value
xdebug.idekey => no value => no value
xdebug.max_nesting_level => 256 => 256
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_enable => Off => Off
xdebug.remote_host => localhost => localhost
xdebug.show_local_vars => Off => Off
```

**Comment by davidalger** [comment]
@adammprost What is the difference of configuration (I'm only seeing one set of values in your post)? Also what problem(s) are the differences causing?

**Comment by mttjohnson** [comment]
The settings to enable xdebug are not copied to the other web nodes. I checked the 15-xdebug.ini on web55 and web54 and it only listed the library file, so all of xdebugs settings were default like what Adam posted above. I think it is skipping the copy of the xdebug.ini on the other web nodes.
