### ISSUE TITLE
Add utility commands like pv and tree to VMs

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#74]
`pv` and `tree` are not available in the web VM. It would nice to have these pre-installed so that I don't have to `sudo yum install` them.

![image](https://cloud.githubusercontent.com/assets/129031/15616313/92cb3260-2408-11e6-924e-2a03a7501d11.png)

**Comment by erikhansen** [comment]
The reason I created this issue is that for some of my projects, I have stage > dev cloning scripts that pipe a mysqldump through `pv`, so running those scripts from within the web VM fails.

**Comment by davidalger** [comment]
Would you mind creating a PR to append these to the list of packages installed in the "generic gust tooling" part of `scripts/node.sh`?
