### ISSUE TITLE
Add ability to specify project name via m2setup.sh

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#75]
Currently the only way to install Magento 2.1 RC using `m2setup.sh` is to do a normal install and then upgrade it to 2.1 using "Upgrade using the command line" instructions on this page: http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC1CE.html

It would be ideal to be able to pass a flag to `m2setup.sh` to use a custom Composer project name (e.g., `magento/project-community-edition=2.1.0-rc1`), per http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.1_RC1CE.html#binstall-using-composerb

**Comment by davidalger** [comment]
I think we should add an `--proj-version` argument to the script to allow passing in a version like so:

`--proj-version=2.1.0-rc1` would result in the following:
```
composer create-project magento/project-community-edition /sites/foo 2.1.0-rc1
```

Not sure how soon I might be able to get to this, so if you'd like to add it via a PR I'd be happy to accept it. :)

**Comment by erikhansen** [comment]
@davidalger - I've submitted a PR to implement this feature. Here is a screenshot demonstrating three test scenarios:

1. Invalid value provided for `--proj-version` flag
2. Valid value provided for `--proj-version` flag
3. No value provided for `--proj-version` flag, so Composer used latest stable release

![bin ssh vcd 189x80-8nziu](https://cloud.githubusercontent.com/assets/129031/15937290/e48d0d78-2e33-11e6-859c-da45974fc3e1.png)
