### ISSUE TITLE
web70 node lacking php ext-zip

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/devenv#79]
We ran into an issue running a composer install for Magento 2 where we got an error indicating ext-zip was not installed and required for installation of Magento 2.

```
vagrant@dev-web70:12:18 PM:/sites/magento2/htdocs$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/product-community-edition 2.0.4 -> satisfiable by magento/product-community-edition[2.0.4].
    - magento/product-community-edition 2.0.4 requires ext-zip * -> the requested PHP extension zip is missing from your system.
```

I searched for how we could install php-zip but didn't find anything specifically on the remi repo, though I did find php-pecl-zip and installing that extension resolved the error we were seeing with composer. Running the following command is our current workaround until this is baked into the dev environment directly.

`sudo yum --enablerepo=remi --enablerepo=remi-php70 install -y php-pecl-zip`

I haven't looked into what the differences are between php-zip and php-pecl-zip or if there are any, but I was seeing some posts online relating to each separately, and something about them being bundled in php-common. So, I don't know if the correct approach would be to include the additional php-pecl-zip package or to look into php-common.

**Comment by davidalger** [comment]
This has been fixed in 3f935ec16. It will be in the next tagged release.
