### ISSUE TITLE
Vagrant 1.8.5 unable to authenticate when building machines

### ISSUE THREAD

**Issue by mttjohnson** [davidalger/devenv#85]
I ran into an issue with a user that had upgraded to 1.8.5 and was unable to create new machines as during the creation process vagrant wasn't able to authenticate to the box after recreating the keys from the base image, and would eventually timeout when spinning up a machine for the first time.

```
==> db: Waiting for machine to boot. This may take a few minutes...
    db: SSH address: 127.0.0.1:2222
    db: SSH username: vagrant
    db: SSH auth method: private key
    db: Warning: Remote connection disconnect. Retrying...
    db: Warning: Remote connection disconnect. Retrying...
    db: Warning: Remote connection disconnect. Retrying...
    db: 
    db: Vagrant insecure key detected. Vagrant will automatically replace
    db: this with a newly generated keypair for better security.
    db: 
    db: Inserting generated public key within guest...
    db: Removing insecure key from the guest if it's present...
    db: Key inserted! Disconnecting and reconnecting using new SSH key...
    db: Warning: Authentication failure. Retrying...
    db: Warning: Authentication failure. Retrying...
    db: Warning: Authentication failure. Retrying...
    db: Warning: Authentication failure. Retrying...
```

This appears to be an issue with Vagrant 1.8.5 specifically in how it is creating the new files inside the VM with the wrong file permissions. https://github.com/mitchellh/vagrant/issues/7642

It looks like this won't get fixed in Vagrant 1.8.5 and is slated to be included in the next version 1.8.6 whenever that gets released. I also saw comments that VirtualBox 5.1 requires Vagrant 1.8.5 or newer, so that would put us at limiting installs to using older versions of Vagrant and VirtualBox until Vagrant releases the newer version and it is tested.

Currently supported until Vagrant's next release:
Vagrant 1.8.4
VirtualBox 5.0.x

**Comment by davidalger** [comment]
Closing since this is an issue with the upstream technology. Thanks for the stellar writeup! Hopefully it wont be too long until vagrant 1.8.6 is released, but until then, if someone runs into it, then they'll have to manually downgrade vagrant versions.
