### ISSUE TITLE
Simple Varnish configuration

### ISSUE THREAD

**Issue by erikhansen** [davidalger/devenv#91]
It would be great to add support to the devenv to make it easy to setup Varnish for different M2 sites. I realize Varnish can be manually configured on the current devenv setup, but it's not trivial to do so, and that barrier has caused pain for me on a number of recent tasks my developers have worked on.

I've run into several situations where not having Varnish easily setup on local development environments has resulted in bugs being pushed to stage, and in order to reproduce and fix them, we've had to go through all the steps required to configure Varnish with the current devenv setup.

I believe it is on the roadmap to remove Apache from the devenv setup (at least the web70 VM?). I expect this enhancement will have to wait until that is done.

**Comment by davidalger** [comment]
@erikhansen Why do you believe Apache has something to do with implementing varnish support?

In it's current state, the only thing which should be needed is adding a proper VCL to the m2 project root and rebuilding your vhosts. 

How did you go about setting up varnish?

**Comment by erikhansen** [comment]
@davidalger I didn't setup Varnish locally—@mttjohnson assisted Kevin in doing so. It seemed like the process took longer to setup than it should have, thus my impetus for creating this issue.

Obviously Varnish can be configured with Apache, I was just suggesting that if Nginx is going to replace Apache any time soon, it may make sense to document or simplify this process in any way until that is done.

Maybe all that is needed is to just document the process of setting up Varnish. Let's discuss in our SC meeting.
